#!/usr/bin/env bash
set -euo pipefail

sudo pacman -S --needed --noconfirm hyprland nvidia nvidia-utils lib32-nvidia-utils egl-wayland noto-fonts

# Modset for nvidia
# Ensure the file exists
CONF_FILE="/etc/modprobe.d/nvidia.conf"
LINE="options nvidia_drm modeset=1"

if [ ! -f "$CONF_FILE" ]; then
	echo "Creating $CONF_FILE"
	echo "" | sudo tee "CONF_FILE" > /dev/null
fi

# Check if line already exists
if ! grep -Pq "\|^s*${LINE// /\\s+}\s*$" "CONF_FILE"; then
	echo "Adding '$LINE' to $CONF_FILE"
	echo "$LINE" | sudo tee -a "$CONF_FILE" > /dev/null
else
	echo "Line already exists in $CONF_FILE"
fi


# Enable KMS late loading
MKINITCONF="/etc/mkinitcpio.conf"
MODULES_NEEDED=(nvidia nvidia_modset nvidia_uvm nvidia_drm)
MODULE_LINE_PATTERN='^MODULES=\((.*)\)$'

# Read the current modules line
current_line=$(grep "^MODULES=" "$MKINITCONF" || true)

# Backup config
sudo cp "$MKINITCONF" "$MKINITCONF.bak"

# If line exists, check and update
if [[ "$current_line"  =~ $MODULE_LINE_PATTERN ]]; then
	current_modules="${BASH_REMATCH[1]}"
	for mod in "${MODULES_NEEDED[@]}"; do
		if ! grep -qw "$mod" <<< "$current_modules"; then
			echo "Adding $mod to MODULES array"
			current_modules="$current_modules $mod"
		fi
	done
	new_line="MODULES=(${current_modules})"
	sudo sed -i "s|^MODULES=.*|$new_line|" "$MKINITCONF"
else
	# MODULES line not found - add it
	echo "MODULES=(${MODULES_NEEDED[*]})" | sudo tee -a "$MKINITCONF" > /dev/null
fi

# Rebuild initramfs
echo "Rebuilding initramfs..."
sudo mkinitcpio -P


# todo remove kms from initcpio hooks
