#!/usr/bin/env bash
set -euo pipefail

paru -S --needed --noconfirm \
    btop \
    openssh \
    pavucontrol \
    flatpak \
    thunar \
    ripgrep \
    less \
    libsecret \
    gnome-keyring \
    cliphist
