#!/usr/bin/env bash
set -euo pipefail

sudo paru -S --needed --noconfirm neovim

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
