#!/usr/bin/env bash
set -euo pipefail

REPO_URL="https://aur.archlinux.org/paru.git"
TMP_DIR="$HOME/develop/.temp/paru-install"

sudo pacman -S --needed --noconfirm base-devel git

if command -V paru >/dev/null 2>&1; then
	echo "paru is already installed" 
	exit 0
fi

echo "Cloning paru into: $TMP_DIR"
rm -rf "$TMP_DIR"
git clone "$REPO_URL" "$TMP_DIR"


cd "$TMP_DIR"
makepkg -si --noconfirm

cd ~
rm -rf "$TMP_DIR"
echo "Cleaned up temporary build files"

if command -V paru >/dev/null 2>&1; then
	echo "Paru successfully installed!"
else
	echo "Paru installation failed"
	exit 1
fi
